# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v3

    - name: Use Node.js 20
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Setup Python
      uses: actions/setup-python@v5.1.0
      with:
      # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.12

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./logs -i smoke tests

    - name: Robot Reporter
      uses: joonvena/robotframework-reporter-action@v2.4
      with:
        # Token to access the API
        gh_access_token: ${{ secrets.GITHUB_TOKEN }}
        # Path to report
        report_path: logs


    
